import esbuild from "esbuild";
import process from "process";
import { builtinModules, createRequire } from "node:module";

const require = createRequire(import.meta.url);
const pkg = require("./package.json");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the Github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const outdir = pkg.config.outdir;

const context = await esbuild.context({
  banner: {
    js: banner
  },
  entryPoints: ["main.ts"],
  bundle: true,
  external: ["obsidian", ...builtinModules],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outdir,
  minify: prod
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
